google:
  oauth2:
    client:
      accessTokenUri: https://accounts.google.com/o/oauth2/v2/auth
      tokenName: oauth_token
      authenticationScheme: query
      clientAuthenticationScheme: form
    authUrl: https://accounts.google.com/o/oauth2/v2/auth
    redirectUri: http://localhost:8080