google:
  oauth2:
    client:
      clientId: 275558456725-1mk6nlcadl9b0l308ktfas3l3o2u0l8c.apps.googleusercontent.com
      accessTokenUri: https://accounts.google.com/o/oauth2/v2/auth
      tokenName: oauth_token
      authenticationScheme: query
      clientAuthenticationScheme: form