# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2.1
orbs:
  awsebcli: sbc-orbs/awsebcli@0.0.3
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/openjdk:8-jdk
    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: ./gradlew build

      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}

      # run tests!
      - run: ./gradlew test

      - store_artifacts:
          path: ~/repo/build
          desination: build_out

  uploadToEB:
    docker:
      - image: circleci/python:3.9.0b2-buster

    working_directory: ~/repo

    steps:
      - awsebcli/install
      - awsebcli/configure
      - aws elasticbeanstalk create-application-version --application-name foobar --version-label $(gradle properties -q | grep "appVersion:" | awk '{print $2}') --region=us-east-1
workflow:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - uploadToEB
